export const CARDS = [
  {
    triggers: ["rejection", "escalation"],
    title: "The Loyalty Bind",
    body: "Children often reject stepparents not because they dislike them, but because acceptance feels like betraying their biological parent. The rejection you're feeling is rarely about you \u2014 it's about the impossible emotional math the child is trying to solve.",
    src: "Braithwaite et al., 2018",
    quote: "\"It was all in my head. I wouldn't want to go out with my dad's family, because I didn't feel comfortable, nor did I feel like I fit in. It wasn't my stepmom's fault, nor my dad's.\"",
    who: "Former stepchild, now 30",
  },
  {
    triggers: ["rejection"],
    title: "What They'll Remember",
    body: "Adult stepchildren consistently report that the things they remember most are NOT grand gestures. It's the ironed shirt. The medicine left without a word. The college fees paid quietly. Things done without any expectation of acknowledgment.",
    quote: "\"She stopped trying to bond. But she still left medicine on my bedside when I was sick. Still paid my college application fees quietly. On my first job interview day, she ironed my shirt and said nothing else. That hurt more than any argument.\"",
    who: "Adult stepchild reflection",
  },
  {
    triggers: ["rejection", "escalation"],
    title: "\"You're Not My Real Parent\"",
    body: "This phrase is the most commonly cited verbal weapon. But research shows it reflects the child's fear of losing their biological parent, not a genuine assessment. Children use it precisely because they know it will land \u2014 which paradoxically means the relationship matters enough to weaponize.",
    quote: "\"I'm sorry I never gave you a chance; a fair, equal chance. I compared you to my father, and thought you were stealing my mother. I was afraid I was losing her. You taught me what a man should be to a woman.\"",
    who: "Adult stepchild, looking back",
  },
  {
    triggers: ["withdrawal"],
    title: "Withdrawal Isn't Rejection",
    body: "When a child withdraws \u2014 leaves the room, goes silent, avoids \u2014 it feels like rejection. But withdrawal is often a self-protective mechanism, not an offensive one. The child may be overwhelmed, processing, or simply not ready. Withdrawal is often a sign they're aware of the relationship, not indifferent to it.",
    quote: "\"When I felt her pullback as a kid, I felt she didn't care if I was there or not as long as she had my dad. And that's what we don't want our bonus children thinking, they aren't wanted.\"",
    who: "Former stepchild perspective",
  },
  {
    triggers: ["neutral", "positive"],
    title: "Neutral Is Progress",
    body: "In stepfamily dynamics, a neutral response IS a positive signal. If the child accepted what you offered without resistance \u2014 even without warmth \u2014 that's movement. The path typically goes: hostility \u2192 avoidance \u2192 tolerance \u2192 neutral acceptance \u2192 occasional warmth. You may be further along than you think.",
    src: "Stepfamily integration typically takes 7\u201312 years. Neutral acceptance is a major milestone.",
  },
  {
    triggers: ["rejection", "withdrawal", "escalation"],
    title: "The 2 AM Truth",
    body: "Right now, everything feels amplified. The rejection feels permanent. The effort feels wasted. But the stepparents who eventually break through are the ones who maintained consistent, low-pressure presence through exactly these moments. Your exhaustion is evidence of your commitment, not your failure.",
    quote: "\"My car broke down on a highway at 2 am. I called him because my phone was dying. He reached in 40 minutes. Didn't lecture me. Just fixed the issue and waited till I got home. Later, he said, 'I know I'm not your first call. I just want to be a reliable one.'\"",
    who: "Adult stepchild about their stepdad",
  },
  {
    triggers: ["rejection", "withdrawal", "escalation"],
    title: "You're Not Becoming Someone Else",
    body: "Feeling angry, resentful, or withdrawn doesn't mean you're becoming a bad stepparent. It means you're a committed adult experiencing sustained emotional labor without feedback. These feelings are a measurement problem, not a character flaw.",
    quote: "\"I was experiencing an identity crisis as a stepmom. Not loving your stepchildren or feeling resentful or jealous does not make you a bad stepmom.\"",
    who: "Stepmom community post",
  },
  {
    triggers: ["neutral", "positive"],
    title: "Anchor This Moment",
    body: "Your brain is wired to weigh negative interactions more heavily than positive ones. This moment \u2014 this neutral or positive response \u2014 is real data. It happened. When the next difficult moment comes, you'll have concrete evidence that progress exists.",
    src: "Negativity bias causes humans to weight negative events 3\u20135\u00d7 more heavily than positive ones.",
  },
  {
    triggers: ["rejection", "escalation"],
    title: "Testing, Not Hating",
    body: "Children in blended families often test stepparents deliberately and repeatedly. They push boundaries, provoke, say hurtful things \u2014 not because they want you gone, but because they need to know if you'll stay. Every test you survive without leaving is an answer they desperately need.",
    quote: "\"I used to test her constantly. Say horrible things just to see if she'd leave. She never did. That's the only reason I trust anyone now.\"",
    who: "Former stepchild, now in therapy",
  },
  {
    triggers: ["withdrawal", "neutral"],
    title: "The Goodnight Door",
    body: "Some of the most powerful stepparenting happens through closed doors. Saying goodnight to someone who won't respond. Making their lunch when they won't say thank you. These aren't failed attempts at connection \u2014 they're deposits into a trust account that compounds over years.",
    quote: "\"I used to slam my door every time she spoke to me. She never stopped knocking. Not to come in \u2014 just to say goodnight through the door. Every night for two years.\"",
    who: "Former stepchild, now 26",
  },
  {
    triggers: ["positive"],
    title: "The Slow Reveal",
    body: "Acceptance in stepfamilies rarely arrives as a single moment. It sneaks in. The child starts calling your house 'home' without thinking. They save you a seat. They text you first. If you're looking for a dramatic turning point, you might miss the dozen tiny ones already happening.",
    quote: "\"The shift didn't happen all at once. One day I just realized I'd started calling her house 'home' without thinking about it.\"",
    who: "Former stepchild, age 24",
  },
  {
    triggers: ["rejection", "withdrawal"],
    title: "The Comparison Trap",
    body: "It's natural to compare yourself to the biological parent. But you're playing a completely different game with different rules. The bio parent has a biological bond and shared history you can't replicate \u2014 and don't need to. Your value isn't in replacing anyone. It's in being an additional person who chose to show up.",
    quote: "\"I hated her for years. Not because she was bad \u2014 because she was there, and my mom wasn't. That's not fair, and I know that now. But a kid doesn't know that.\"",
    who: "Adult stepchild, age 28",
  },
  {
    triggers: ["neutral", "positive", "withdrawal"],
    title: "Different Love Is Still Love",
    body: "Nobody tells you this: you don't have to feel the same way about your stepchildren as you would about biological children. The expectation of instant parental love creates guilt where none is needed. What matters isn't the type of feeling \u2014 it's the consistency of showing up.",
    quote: "\"You don't have to love your stepkids the same way you love your bio kids. Different love is still love. I wish someone had given me permission to feel that earlier.\"",
    who: "Stepmom, blended family",
  },
  {
    triggers: ["rejection", "escalation"],
    title: "The Invisible Scoreboard",
    body: "You may feel like you're losing because the score looks terrible today. But stepfamily relationships aren't scored in days or weeks. They're scored in decades. Many adult stepchildren describe a moment in their twenties or thirties when everything their stepparent did finally clicked \u2014 all at once, years later.",
    quote: "\"When I got married, I asked my stepdad to walk me down the aisle. My mom cried. He cried. I cried. He had waited seventeen years for that moment and never once asked for it.\"",
    who: "Adult stepdaughter",
  },
  {
    triggers: ["withdrawal", "neutral"],
    title: "Presence Over Performance",
    body: "The most effective stepparenting strategy isn't trying harder \u2014 it's simply being present without agenda. Not performing warmth. Not forcing activities. Just existing in the same space without pressure. Children eventually notice the difference between someone who demands connection and someone who just makes themselves available for it.",
    quote: "\"He never tried to be my dad. He just kept showing up. Drove me places. Fixed things. Asked how school was, even when I gave one-word answers for three years straight. I didn't appreciate it until I was 25.\"",
    who: "Former stepchild about stepdad",
  },
  {
    triggers: ["rejection", "withdrawal", "escalation"],
    title: "The Regret That Comes Later",
    body: "Many adult stepchildren carry deep regret about how they treated their stepparent. They couldn't see it at the time \u2014 they were children navigating an impossible situation. But the guilt arrives later, sometimes much later. Your patience now is saving them from worse regret later.",
    quote: "\"I wrote my stepmom a letter when I turned 30. Just to say sorry. And thank you. She framed it.\"",
    who: "Adult stepchild",
  },
  {
    triggers: ["rejection", "escalation"],
    title: "You Chose This. That Matters.",
    body: "Biological parents don't choose their children \u2014 it just happens. But you chose to be here. Every difficult day is a day you could have walked away and didn't. Children eventually understand the difference between obligation and choice. When they do, it lands hard.",
    quote: "\"He came to every single game. Even when I pretended he wasn't there. Especially when I pretended he wasn't there.\"",
    who: "Former stepchild about stepdad",
  },
  {
    triggers: ["neutral", "positive"],
    title: "The Corner Piece",
    body: "The moments that matter most are absurdly small. Noticing which piece of cake they prefer. Knowing their shoe size. Having their favourite snack ready without being asked. These tiny acts of paying attention are what children actually remember when they look back \u2014 not the big trips or expensive gifts.",
    quote: "\"The thing I remember most isn't any big conversation. It's that he always saved me the corner piece of the brownies. Every single time. He noticed that about me when nobody else did.\"",
    who: "Adult stepchild, age 32",
  },
  {
    triggers: ["withdrawal", "rejection"],
    title: "Okay Is Enough",
    body: "Not every stepparent-stepchild relationship becomes warm. Some settle into a comfortable, respectful distance \u2014 and research shows that's a perfectly valid outcome. Letting go of the fantasy of a close bond can actually be the thing that makes a closer bond possible, because it removes the pressure the child is resisting.",
    quote: "\"The relationship didn't get good. It got okay. And okay turned out to be more than enough.\"",
    who: "Adult stepchild about realistic outcomes",
  },
  {
    triggers: ["rejection", "withdrawal", "escalation"],
    title: "Your Partner's Child, Your Grief",
    body: "Nobody talks about stepparent grief \u2014 the loss of the family life you imagined, the mourning of a relationship you can't force into existence. This grief is real and valid. Acknowledging it doesn't mean giving up. It means being honest about the emotional cost of what you're doing, so you can sustain it.",
    quote: "\"The hardest part wasn't that she rejected me. It was that I started to believe I was the problem. I wasn't. The situation was the problem.\"",
    who: "Stepparent of 8 years",
  },
  {
    triggers: ["neutral", "positive"],
    title: "Right On Track",
    body: "If you're a few years in and the relationship feels 'fine but not close,' you're not failing \u2014 you're precisely on the documented timeline. Researchers describe 7\u201312 years for full integration. Most stepparents don't know this and spend years feeling like they're behind when they're actually right on schedule.",
    quote: "\"Nobody told me that 'doing fine' was a realistic best-case for the first five years. I kept thinking I was failing when I was actually right on track.\"",
    who: "Stepdad, year 7",
  },
  {
    triggers: ["rejection", "withdrawal"],
    title: "Fear Dressed As Anger",
    body: "When a child lashes out at a stepparent, it almost always looks like anger. But underneath most stepchild anger is fear \u2014 fear of losing their parent's attention, fear of their family changing further, fear of betraying their other parent by liking you. The anger is just the only emotion they know how to express safely.",
    quote: "\"I wish someone had told my stepdad that my silence wasn't rejection. I was just scared that if I loved him, it meant I didn't love my dad anymore.\"",
    who: "Former stepchild, now 27",
  },
];
